title: <p align="center"> Satyam Singh <\p>
logo: /assets/img/logo.png
description: Senior Data Engineer at Zalando | Ex McKinsey & Company | Ex Cognizant
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
